
CREATE TABLE TB_CURSOS
(
 ID							 INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,CURSO						 VARCHAR(50) UNIQUE
,NOME						 VARCHAR(50) NOT NULL
,EXTRACURRICULAR			 CHAR(1) NOT NULL CHECK (EXTRACURRICULAR IN ('S', 'N'))
)
GO

CREATE TABLE TB_ALUNOS
(
 RA							 INT PRIMARY KEY NOT NULL
,NOME						 VARCHAR(150) NOT NULL 
,CPF						 VARCHAR(11) UNIQUE NOT NULL
,MAE						 VARCHAR(150) NOT NULL
,PAI						 VARCHAR(150)
,SEXO						 VARCHAR(20) CHECK (SEXO IN ('Masculino', 'Feminino', 'Não informado')) NOT NULL
,DDD						 CHAR(2) NOT NULL
,TELEFONE					 VARCHAR(15) NOT NULL
,EMAIL						 VARCHAR(150) NOT NULL
,CEP						 VARCHAR(10) NOT NULL
,LOGRADOURO					 VARCHAR(150) NOT NULL
,NUMERO						 VARCHAR(10) NOT NULL
,COMPLEMENTO				 VARCHAR(50) 
,CIDADE						 VARCHAR(50) NOT NULL
,UF							 CHAR(2) NOT NULL
,SITUACAO					 VARCHAR(10) DEFAULT 'Ativo'
)							 
GO

CREATE TABLE TB_RESPONSAVEIS 
(							 
 ID							 INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,NOME						 VARCHAR(150) NOT NULL
,CPF						 VARCHAR(15) UNIQUE NOT NULL 
,DDD						 CHAR(2) NOT NULL
,TELEFONE					 VARCHAR(20) NOT NULL
,EMAIL						 VARCHAR(150) NOT NULL
,RA							 INT NOT NULL
FOREIGN KEY (RA)			 REFERENCES TB_ALUNOS(RA)
)							 
GO							 
							 
CREATE TABLE TB_DISCIPLINAS	 
(							 
 ID							 INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,NOME						 VARCHAR(80) NOT NULL
,CARGA_HORARIA				 INT NOT NULL
,ID_CURSO					 INT
FOREIGN KEY (ID_CURSO)		 REFERENCES TB_CURSOS(ID)
)
GO

CREATE TABLE TB_MATRICULAS
(
 RA							 INT NOT NULL
,ID_CURSO					 INT NOT NULL
,NOME_DO_CURSO				 VARCHAR(50) NOT NULL
,TURMA						 VARCHAR(10) NOT NULL
,TURNO						 CHAR(1) NOT NULL
,ID_DISCIPLINA				 INT NOT NULL
,NOME_DA_DISCIPLINA			 VARCHAR(100) NOT NULL
,SERIE						 INT NOT NULL
,DATA_DA_MATRICULA			 DATETIME NOT NULL
,FOREIGN KEY (RA)			 REFERENCES TB_ALUNOS(RA)
)
GO

CREATE TABLE TB_MATRICULAS_CURSOS_EXTRACURRICULARES
(
 RA							 INT NOT NULL
,ID_CURSO					 INT NOT NULL
,NOME_DO_CURSO				 VARCHAR(50) NOT NULL
,ID_DISCIPLINA				 INT NOT NULL
,NOME_DA_DISCIPLINA			 VARCHAR(100) NOT NULL
,DATA_DA_MATRICULA			 DATETIME NOT NULL
,FOREIGN KEY (RA)			 REFERENCES TB_ALUNOS(RA)
)
GO

CREATE TABLE TB_HISTORICOS
(
 RA							 INT NOT NULL
,ID_CURSO					 INT NOT NULL
,NOME_DO_CURSO				 VARCHAR(50) NOT NULL
,TURMA						 VARCHAR(10) NOT NULL
,TURNO						 CHAR(1) NOT NULL
,ID_DISCIPLINA				 INT NOT NULL
,NOME_DA_DISCIPLINA			 VARCHAR(100) NOT NULL
,SERIE						 INT NOT NULL
,NOTA						 DECIMAL(4,2) NOT NULL
,FREQUENCIA					 DECIMAL(4,2) NOT NULL
,SITUACAO					 VARCHAR(10) CHECK(SITUACAO IN('Concluído', 'Reprovado')) NOT NULL
,DATA_DE_INSERCAO			 DATETIME NOT NULL
,FOREIGN KEY (RA)			 REFERENCES TB_ALUNOS(RA) 
)
GO

CREATE TABLE TB_TURMAS
(
 ID							 INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,TURMA						 VARCHAR(10) UNIQUE NOT NULL
,ID_CURSO					 INT NOT NULL
,SERIE						 INT NOT NULL
,FOREIGN KEY (ID_CURSO)		 REFERENCES TB_CURSOS(ID)
)
GO

CREATE TABLE TB_AUXILIAR_MATRICULA 
(
 ID_SESSAO					 INT
,RA_ALUNO					 VARCHAR(20)
)
